# Generated by Django 4.0.3 on 2023-09-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=200)),
                ('pageCount', models.IntegerField()),
                ('publishedDate', models.DateField()),
                ('shortDescription', models.CharField(max_length=250)),
                ('longDescription', models.CharField(max_length=250)),
                ('categories', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('publishedDate',),
            },
        ),
    ]
